### ISSUE TITLE
Price indexes varying by geographical area

### ISSUE THREAD

**Issue by gcasamat** [andykrause/hpiR#70]
Hi, 
I have transactions data for a whole region and would like to construct house prices indexes that vary by geographical area (city). 
Is this possible with the hpiR package? 
Thank you!

**Comment by andykrause** [comment]
The package itself doesn't have a 'partitioning function', but you should be able to do something like:

```
cities_list <- split(transactions_df, transactions_df$city_name)
cities_hpi <- purrr::map(.x = cities_list,
                                          .f = rtIndex,
                                          ... (your other parameters))
```

Let me know if you need a more in depth example.

**Comment by gcasamat** [comment]
This looks great. Thank you!

**Comment by gcasamat** [comment]
Hi.
I tried what you suggest and got the error message : `Error: Can't convert a `hpiindex` object to function`
Moreover, I have also an error message when executing plot() with an annual periodicity (it works fine with a monthly periodicity) : 
```
Error in data.frame(x = x$numeric, y = as.numeric(x$value), imp = x$imputed,  : 
  arguments imply differing number of rows: 0, 10
```

**Comment by gcasamat** [comment]
I'm sorry. The first error message was due to a misunderstanding on my side. I corrected, but now get the following error: 
```
"mod_spec" argument must be of class "formula"
Error in hpiModel.hed(model_type = "hed", hpi_df = hed_trans, mod_spec = hed_spec,  : 
```

**Comment by gcasamat** [comment]
I managed to get an output by using .f = modelToIndex. What I don't understand however is that I get the same index series for the two regions in my data (my dataset has been split on these two regions).

**Comment by gcasamat** [comment]
I managed to get it work with .f = hedIndex, sorry for all these messages.
So the only remaining error concerns  plot() with an annual periodicity. 
Thank you.

**Comment by andykrause** [comment]
@gcasamat.  Sorry for all the trouble here.  Can you give me a bit more details on the issue you are having with plot()?

**Comment by andykrause** [comment]
Closing due to lack of response from reporter.
