### ISSUE TITLE
Enhancement request: manual weights for properties.

### ISSUE THREAD

**Issue by rjm001** [andykrause/hpiR#71]
Awesome package!

I am interested in applying different weights to the properties I have in my data set. That is, suppose a house identical to house A sold 8 times for the same initial and final prices across the same time periods. Rather than enter 8 identical rows for house A, I want to be able to assign a weight matrix (of equal rows as the data set), with coefficient 8 for house A, that captures the fact that house A really sold 8 more times than its one row suggests. Similar to weighted least squares. Do you know an easy way to do this? I can help build this.

**Comment by andykrause** [comment]
Thanks @rjm001!

The `hpimodel()` function can take an option 'weights' argument. 

For example, imagine you are estimating an index with a hedonic model. (using the provided data in the package).  The following would give you a weighted version:

`w = c(rep(2,2000), rep(1, 3348)
model = hpiModel(model_type = 'hed',
                                hpi_df = sales_hhdf,
                                estimator = 'base',
                               dep_var = 'price',
                               ind_var = c('tot_sf', 'beds', 'baths'),
                               log_dep = TRUE, 
                               wgts=w)`

If that isn't working for your particular case, please do feel free to issue a PR here...I'm always happy to have help.  And thanks for using the package!

**Comment by andykrause** [comment]
Closing due to no followup from reporter.
