### ISSUE TITLE
Annualised data index not working

### ISSUE THREAD

**Issue by melville1808** [andykrause/hpiR#72]
df$index$number is equal to NULL, when it should be a numeric data.

Example -
```
data(ex_sales)

df <- rtIndex(trans_df = ex_sales,
                periodicity = 'monthly',
                min_date = '2010-06-01',
                max_date = '2015-11-30',
                adj_type = 'clip',
                date = 'sale_date',
                price = 'sale_price',
                trans_id = 'sale_id',
                prop_id = 'pinx',
                seq_only = TRUE,
                estimator = 'robust',
                log_dep = TRUE,
                trim_model = TRUE,
                max_period = 48,
                smooth = FALSE)
plot(df)
```

this provides the desired result (and is from the vignette).

Whereas
```
data(ex_sales)

df <- rtIndex(trans_df = ex_sales,
                periodicity = 'yearly',
                min_date = '2010-06-01',
                max_date = '2015-11-30',
                adj_type = 'clip',
                date = 'sale_date',
                price = 'sale_price',
                trans_id = 'sale_id',
                prop_id = 'pinx',
                seq_only = TRUE,
                estimator = 'robust',
                log_dep = TRUE,
                trim_model = TRUE,
                max_period = 48,
                smooth = FALSE)
plot(df)

```

produced the error: 
Error in data.frame(x = x$numeric, y = as.numeric(x$value), imp = x$imputed,  : 
  arguments imply differing number of rows: 0, 48

It looks like the index is being created correctly, but the df$index$numeric field used in the plot is not.

**Comment by andykrause** [comment]
Thanks for reporting this.  Interestingly the plot() works for me...but I do see the x$numeric as being all NULL.  Let me take a look and get back to you.

**Comment by andykrause** [comment]
@melville1808 Do you have the latest version (0.3.4)?  In this version, the plot function will use `period` instead of the null numeric and should work. 

You can get the new version with `devtools::install_github("andykrause/hpiR"`.  Apologies as the CRAN version is slightly out of data 0.3.2 (haven't had time to update it).  

Thanks again for reporting.

**Comment by andykrause** [comment]
Also, I do still need to remove the remnant $numeric column as well as push an update to CRAN, so I'll leave this ticket open.

**Comment by melville1808** [comment]
Thanks, that fixes the problem.
